name = "healthcare-test-agent"
version = "0.1.0"
description = "Test case generater for Healthcare"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.14.1",
    "pandas>=2.3.2",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
]
